#Testing
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: deploy01
  name: deploy01
spec:
  replicas: 9
  selector:
    matchLabels:
      run: deploy01
  template:
    metadata:
      labels:
        run: deploy01
    spec:
      containers:
      - image: sreeharshav/rollingupdate:v5
        name: deploy01
